
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILED = 'LOAD_POSTS_FAILED'

export const LOAD_POSTS_BY_SLUG_SUCCESS = 'LOAD_POSTS_BY_SLUG_SUCCESS'
export const LOAD_POSTS_BY_SLUG_FAILED = 'LOAD_POSTS_BY_SLUG_FAILED'



export const LOAD_MEDIA_SUCCESS = 'LOAD_MEDIA_SUCCESS'
export const LOAD_MEDIA_FAILED = 'LOAD_MEDIA_FAILED'

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'

export const LOAD_MEDIA_BY_ID_SUCCESS = 'LOAD_MEDIA_BY_ID_SUCCESS'
